captainVersion: 4
services:
    $$cap_appname:
        image: upshift/dolibarr:$$cap_dolibarr-version
        volumes:
            - $$cap_appname-html:/var/www/html
            - $$cap_appname-docs:/var/www/documents
        restart: always
        environment:
            DOLI_DB_HOST: $$cap_appname-db
            DOLI_DB_NAME: $$cap_db_database
            DOLI_DB_ROOT_LOGIN: root
            DOLI_DB_ROOT_PASSWOORD: $$cap_db_rootpass
            DOLI_DB_USER: $$cap_db_user
            DOLI_DB_TYPE: mysql
            DOLI_DB_PASSWORD: $$cap_db_pass
            DOLI_ADMIN_LOGIN: $$cap_admin-login
            DOLI_ADMIN_PASSWORD: $$cap_admin-pass
            DOLI_URL_ROOT: http://$$cap_appname.$$cap_root_domain
caproverOneClickApp:
    variables:
        - id: $$cap_dolibarr-version
          label: Dolibarr Version
          defaultValue: '11.0'
          description: Check out their docker page for the valid tags https://hub.docker.com/r/upshift/dolibarr/tags?page=1&ordering=last_updated
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_admin-login
          label: Dolibarr Admin Login
          defaultValue: admin
          description: The login of the fisrt admin user of Dolibarr
          validRegex: /.{1,}/
        - id: $$cap_admin-pass
          label: Dolibarr Admin Password
          description: The password of the first admin user of Dolibarr
          validRegex: /.{1,}/
        - id: $$cap_appname-db
          label: MySQL Hostname
          description: The hostname of the MySQL Database
          validRegex: /.{1,}/
        - id: $$cap_db_rootpass
          label: MySQL Root Password
          description: The Root password of the MySQL Database
          validRegex: /.{1,}/
        - id: $$cap_db_database
          label: MySQL DATABASE Name
          description: The name of the MySQL Database
          validRegex: /.{1,}/
        - id: $$cap_db_user
          label: MySQL User
          description: The user of the MySQL Database
          validRegex: /.{1,}/
        - id: $$cap_db_pass
          label: MySQL Password
          description: The password of the MySQL Database
          validRegex: /.{1,}/
    instructions:
        start: Dolibarr is an Open Source ERP & CRM for Business
        end: Dolibarr is deployed and available as srv-captain--$$cap_appname:8080 to other apps.
    displayName: Dolibarr
    description: Open Source ERP & CRM for Business (SME or large companies, freelancers, foundations)
    documentation: https://hub.docker.com/r/upshift/dolibarr
